# ghostcloud-cosmos CI
# The Lifted Initiative
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    parameters:
      node_version:
        type: string
    executor:
      name: node/default
      tag: << parameters.node_version >>
    resource_class: large
    steps:
      - checkout
      - run:
          name: Yarn Set Version Stable
          command: |                                                                                                                                                      
           npm install -g yarn || echo "Yarn may have already been installed."                                                                                            
           yarn set version stable
      - run:
          command: node -v && yarn -v
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build

workflows:
  ci:
    jobs:
      - build:
          node_version: "20.9.0"